Update code_checking_workflow.yml

diff --git a/.github/workflows/code_checking_workflow.yml b/.github/workflows/code_checking_workflow.yml
--- a/.github/workflows/code_checking_workflow.yml
+++ b/.github/workflows/code_checking_workflow.yml
@@ -28,17 +28,17 @@ jobs:
 
       - name: Install dependencies
         run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt || echo "Failed to install some dependencies"
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt || echo "Failed to install some dependencies"
 
-        # Check for TensorFlow 2.8.0, and install the latest version if not available
-        if ! pip install tensorflow==2.8.0; then
-          echo "TensorFlow 2.8.0 not available, installing the latest version"
-          pip install tensorflow
-        fi || echo "Failed to install TensorFlow"
+          # Check for TensorFlow 2.8.0, and install the latest version if not available
+          if ! pip install tensorflow==2.8.0; then
+            echo "TensorFlow 2.8.0 not available, installing the latest version"
+            pip install tensorflow
+          fi || echo "Failed to install TensorFlow"
 
-        # Display the installed TensorFlow version
-        python -c "import tensorflow as tf; print('Installed TensorFlow version:', tf.__version__)"
+          # Display the installed TensorFlow version
+          python -c "import tensorflow as tf; print('Installed TensorFlow version:', tf.__version__)"
 
       - name: Get latest versions
         id: versions
